// GENERATED by scripts/media/build.mjs from scripts/media/sources.json. Do not edit by hand (see docs/MEDIA.md).
import type { MediaItem } from './media-types';

export const MEDIA_ITEMS: readonly MediaItem[] = [
  {
    "id": "basilica-facade",
    "topic": "basilica",
    "subject": "facade",
    "alt": "The west facade of the Basilica of the Annunciation in Nazareth under a deep blue sky",
    "width": 2560,
    "height": 1447,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADQAQCdASoQAAkAA4BaJQBOgB4NSpWp8AD+2p8pv7vPjmptzQXv5aPq+YzvHgj3DOTZuKITEvQ+wOvXIvvsBYK+NqbH3tU6wsXKAAAA",
    "focal": {
      "x": 50,
      "y": 40
    },
    "og": true,
    "credit": "Berthold Werner / Wikimedia Commons, CC BY-SA 3.0",
    "author": "Berthold Werner",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Nazaret_Verkuendigungsbasilika_BW_2010-09-23_13-02-20_stitch3.jpg",
    "file": "Nazaret Verkuendigungsbasilika BW 2010-09-23 13-02-20 stitch3.jpg"
  },
  {
    "id": "basilica-night-view",
    "topic": "basilica",
    "subject": "night",
    "alt": "The floodlit Basilica of the Annunciation above the lights of Nazareth at night",
    "width": 2560,
    "height": 1714,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADwAQCdASoQAAsAA4BaJQBOgCHiB58BMIAA/veZHFzOjcV8qZnjD1Zb/WTxDadGZx3ZFtCRL7QgoV82NTPrDJG5CZXq3tb6aiDE4hFhtbVRHNtd6pJi0/2AAAA=",
    "focal": {
      "x": 30,
      "y": 72
    },
    "og": true,
    "credit": "Zxc0505 / Wikimedia Commons, CC BY-SA 3.0",
    "author": "Zxc0505",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Basilica_of_the_Annunciation_night_view.JPG",
    "file": "Basilica of the Annunciation night view.JPG"
  },
  {
    "id": "basilica-dome-palms",
    "topic": "basilica",
    "subject": "dome",
    "alt": "The conical dome of the Basilica of the Annunciation rising above palm trees",
    "width": 2560,
    "height": 1393,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoQAAkAA4BaJbACdADprT5QZwAA/shvX1v87U7WPQmEth5mltBH142rhr6wr532lDKG/VZgeD75kvDz0JWVgt69LDh7ZQAA",
    "focal": {
      "x": 50,
      "y": 45
    },
    "og": true,
    "credit": "Zairon / Wikimedia Commons, CC BY-SA 4.0",
    "author": "Zairon",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Nazareth_Verk%C3%BCndigungskirche_Kuppel_1.JPG",
    "file": "Nazareth Verkündigungskirche Kuppel 1.JPG"
  },
  {
    "id": "basilica-dome-rooftops",
    "topic": "basilica",
    "subject": "dome",
    "alt": "The dome and facade of the Basilica seen from above, among the rooftops of Nazareth",
    "width": 1920,
    "height": 1424,
    "widths": [
      640,
      1280,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAAAQAgCdASoQAAwAA4BaJZQCdAEWKimC/x0AAP0rt1gQotWahdqM1Zx5Obp5I9BdqF3IyoIujSMMtUG2nh58nOnNA5IhBN7BioAAAA==",
    "focal": {
      "x": 38,
      "y": 50
    },
    "og": false,
    "credit": "Zairon / Wikimedia Commons, CC BY-SA 4.0",
    "author": "Zairon",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Nazareth_Blick_auf_die_Verk%C3%BCndigungskirche_2.JPG",
    "file": "Nazareth Blick auf die Verkündigungskirche 2.JPG"
  },
  {
    "id": "basilica-courtyard-dusk",
    "topic": "basilica",
    "subject": "courtyard",
    "alt": "Strings of lights over the courtyard of the Basilica of the Annunciation at dusk",
    "width": 1920,
    "height": 1440,
    "widths": [
      640,
      1280,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQAgCdASoQAAwAA4BaJYgCdADdRKLH7sXwAP6JSMTt9r8lfdT5UIojdjbQUSVUvCDSEoYVdZsuycu759hoV6EjTvAg70Ax+y7quQiqcKX9Zg56IAAAAA==",
    "focal": {
      "x": 55,
      "y": 60
    },
    "og": false,
    "credit": "Mksg1 / Wikimedia Commons, CC BY-SA 4.0",
    "author": "Mksg1",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Nazareth_Church_of_Annunciation.jpg",
    "file": "Nazareth Church of Annunciation.jpg"
  },
  {
    "id": "basilica-spring-flowers",
    "topic": "basilica",
    "subject": "exterior",
    "alt": "The Basilica of the Annunciation above a hillside of yellow spring wildflowers",
    "width": 1920,
    "height": 1280,
    "widths": [
      640,
      1280,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAwAgCdASoQAAsAA4BaJbACdAEPEMWqWKZ0AAD+CxMBtWe2SbbvObNQoLQF20a+VBo83mV7podeFM6LeltDOCxpUzOki4tvFJkdwdxkLD8gN3Del0AAAA==",
    "focal": {
      "x": 62,
      "y": 42
    },
    "og": false,
    "credit": "Adam Jones / Wikimedia Commons, CC BY-SA 2.0",
    "author": "Adam Jones",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:View_over_Basilica_of_the_Annunciation_from_Arab_Cemetery_-_Nazareth_-_Israel_(5699606334).jpg",
    "file": "View over Basilica of the Annunciation from Arab Cemetery - Nazareth - Israel (5699606334).jpg"
  },
  {
    "id": "basilica-upper-nave",
    "topic": "basilica",
    "subject": "interior",
    "alt": "The nave of the upper church of the Basilica of the Annunciation, looking towards the apse mosaic",
    "width": 1920,
    "height": 1280,
    "widths": [
      640,
      1280,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAQAgCdASoQAAsAA4BaJQBOgMVztS+kGCsAAP7l96+YBT/FwT9pzJT3+uLnH2IEk3a9FBIVryn1G0qLzJ4deFS+jq5aamHLvCGI0J63gY+df3XpLulFDRIoXQClMAAA",
    "focal": {
      "x": 50,
      "y": 40
    },
    "og": false,
    "credit": "Dennis G. Jarvis / Wikimedia Commons, CC BY-SA 2.0",
    "author": "Dennis G. Jarvis",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Nazareth._Israel-05281_-_Upper_Church_(33580000733).jpg",
    "file": "Nazareth. Israel-05281 - Upper Church (33580000733).jpg"
  },
  {
    "id": "basilica-dome-interior",
    "topic": "basilica",
    "subject": "ceiling",
    "alt": "The ribbed concrete dome of the Basilica seen from inside, shaped like an upturned lily",
    "width": 1920,
    "height": 1400,
    "widths": [
      640,
      1280,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQAgCdASoQAAwAA4BaJYwCw7EfvTp8cpnYAP7OBoqiJsuwi98rqKzroZa3r/dx7tn4A1IJqGG6n19qb5aMHmXZBqhiWtpixEuu++ZsE7kCOE0peIAAAA==",
    "focal": {
      "x": 50,
      "y": 45
    },
    "og": false,
    "credit": "Zairon / Wikimedia Commons, CC BY-SA 4.0",
    "author": "Zairon",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Nazareth_Verk%C3%BCndigungskirche_Innen_Unterkirche_Kuppel_1.JPG",
    "file": "Nazareth Verkündigungskirche Innen Unterkirche Kuppel 1.JPG"
  },
  {
    "id": "basilica-grotto-altar",
    "topic": "basilica",
    "subject": "grotto",
    "alt": "The altar of the Grotto of the Annunciation, set into the rock of the lower church",
    "width": 1920,
    "height": 1280,
    "widths": [
      640,
      1280,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAACwAQCdASoQAAsAA4BaJZgCdACirTMAAP7BnNILJoLY5KTuNxDHVqiutGTwJYWbaTq2ivdMf2Eh2r9gfnv0vhndtT8YsKCsdSr03eswAAA=",
    "focal": {
      "x": 50,
      "y": 55
    },
    "og": false,
    "credit": "Dennis G. Jarvis / Wikimedia Commons, CC BY-SA 2.0",
    "author": "Dennis G. Jarvis",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Nazareth._Israel-05317_-_Grotto_Altar_(34390259885).jpg",
    "file": "Nazareth. Israel-05317 - Grotto Altar (34390259885).jpg"
  },
  {
    "id": "basilica-lower-church",
    "topic": "basilica",
    "subject": "interior",
    "alt": "The lower church of the Basilica of the Annunciation around the ancient grotto",
    "width": 1920,
    "height": 1280,
    "widths": [
      640,
      1280,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACwAQCdASoQAAsAA4BaJQBOgA+V+ZewAP7qS6BER837knhmx+wCJZGejPGaRllEXnsVlhMI2vA6BVwmT/RsQCPsg5QlDWDMapjgiF33LJ3+gAAA",
    "focal": {
      "x": 50,
      "y": 55
    },
    "og": false,
    "credit": "Larry Koester / Wikimedia Commons, CC BY 2.0",
    "author": "Larry Koester",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Basilica_of_Annunciation_-_Nazareth_-_lower_level_(1)_(37173519901).jpg",
    "file": "Basilica of Annunciation - Nazareth - lower level (1) (37173519901).jpg"
  },
  {
    "id": "basilica-night-front",
    "topic": "basilica",
    "subject": "night",
    "alt": "The facade and dome of the Basilica of the Annunciation lit up at night",
    "width": 1920,
    "height": 1440,
    "widths": [
      640,
      1280,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAQCdASoQAAwAA4BaJYwCdAEOI3KYRMAA/vkT9SB+umAtLslVx4WW3jMVv650unNIHKW0aG2alvUn5WfvX7OhgJxn7DPd6YJfM4SpwGk20qAA",
    "focal": {
      "x": 50,
      "y": 38
    },
    "og": false,
    "credit": "Fallaner / Wikimedia Commons, CC BY-SA 4.0",
    "author": "Fallaner",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Holy_Land_2022_(1)_P570_Nazareth_Church_of_the_Annunciation.jpg",
    "file": "Holy Land 2022 (1) P570 Nazareth Church of the Annunciation.jpg"
  },
  {
    "id": "stjoseph-facade",
    "topic": "stjoseph",
    "subject": "exterior",
    "alt": "The stone facade of the Church of St. Joseph beside the Basilica of the Annunciation",
    "width": 1920,
    "height": 1440,
    "widths": [
      640,
      1280,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAACwAQCdASoQAAwAA4BaJYgCdADNp7l0AP72k/Da00RzJmt5zj4TTYt3tpx5rhiwLZEPZ+sl1yWzU8LzGeobBmge0xW1n3g9t3+AHRRJbAvfNOZxEkipAeWe2d8pAAAA",
    "focal": {
      "x": 50,
      "y": 55
    },
    "og": false,
    "credit": "Elaimon / Wikimedia Commons, CC BY-SA 4.0",
    "author": "Elaimon",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Saint_joseph_church.jpg",
    "file": "Saint joseph church.jpg"
  },
  {
    "id": "stjoseph-arcades",
    "topic": "stjoseph",
    "subject": "interior",
    "alt": "Round arches and stained-glass windows inside the Church of St. Joseph",
    "width": 1920,
    "height": 1280,
    "widths": [
      640,
      1280,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAABwAgCdASoQAAsAA4BaJaACdAYv/2deiP7ofJ4AAP7EYHMFk2pNXcawdPo03rAql1X2S9JfVxJOeZW/n2z20Hh1PKxqjUZbDzmXN0aHhfGwOnYjZg8SaOGkXXiY9HWn45Kr6AAA",
    "focal": {
      "x": 50,
      "y": 45
    },
    "og": false,
    "credit": "Zicong Deng / Wikimedia Commons, CC BY-SA 3.0",
    "author": "Zicong Deng",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Church_Nazareth_2.JPG",
    "file": "Church Nazareth 2.JPG"
  },
  {
    "id": "stjoseph-nave",
    "topic": "stjoseph",
    "subject": "interior",
    "alt": "The nave of the Church of St. Joseph, with its Romanesque arches and timber roof, looking to the apse",
    "width": 1920,
    "height": 1440,
    "widths": [
      640,
      1280,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAABwAgCdASoQAAwAA4BaJZACdAYxZzYPm6aoWrIAAP2/BjUeJe01zmlixZ5z7/YfBCzEEShZTHC+EPeuqU7pu0CJNlQWFJI/+07BNSO+Wse3jkexk8g6DgBPHz7A2/uLLIayWBNAAAA=",
    "focal": {
      "x": 50,
      "y": 50
    },
    "og": false,
    "credit": "Britchi Mirela / Wikimedia Commons, CC BY-SA 4.0",
    "author": "Britchi Mirela",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:ISRAEL;_Nazareth;_Church_of_St._Joseph_(2).JPG",
    "file": "ISRAEL; Nazareth; Church of St. Joseph (2).JPG"
  },
  {
    "id": "stjoseph-columns",
    "topic": "stjoseph",
    "subject": "interior",
    "alt": "Carved columns and the timber roof of the Church of St. Joseph",
    "width": 1920,
    "height": 1440,
    "widths": [
      640,
      1280,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAADQAQCdASoQAAwAA4BaJbACdADQlE1SAAD+9pP34u6+6ylsb+R7z0s//Jr540kUvW6OH+16OE0k6uDaAC4I/lWa0B/2gy9rdu0NEavp+lfpNEbigIUjfvez5uOTdfB5KV5kEBQuFLAAAA==",
    "focal": {
      "x": 38,
      "y": 45
    },
    "og": false,
    "credit": "Britchi Mirela / Wikimedia Commons, CC BY-SA 4.0",
    "author": "Britchi Mirela",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:ISRAEL;_Nazareth;_Church_of_St._Joseph_(3).JPG",
    "file": "ISRAEL; Nazareth; Church of St. Joseph (3).JPG"
  },
  {
    "id": "greek-church-exterior",
    "topic": "greek",
    "subject": "exterior",
    "alt": "The Greek Orthodox Church of the Annunciation and its bell tower, seen across the square",
    "width": 2560,
    "height": 1529,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADwAQCdASoQAAoAA4BaJQBOgBbz+IO+agAA+JBbCl/BQ3qK2KrSM4Yzv5yqWyQ7Jzl6gNhMzjCodanq35ctqkJOx7z5gcN+AAA=",
    "focal": {
      "x": 45,
      "y": 50
    },
    "og": true,
    "credit": "Gerd Eichmann / Wikimedia Commons, CC BY-SA 4.0",
    "author": "Gerd Eichmann",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Nazareth-Griechisch-orthodoxe_Verkuendigungskirche-02-2010-gje.jpg",
    "file": "Nazareth-Griechisch-orthodoxe Verkuendigungskirche-02-2010-gje.jpg"
  },
  {
    "id": "greek-church-porch",
    "topic": "greek",
    "subject": "bellTower",
    "alt": "The stone church of St. Gabriel with its bell tower and arched porch",
    "width": 1920,
    "height": 1502,
    "widths": [
      640,
      1280,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQAQCdASoQAA0AA4BaJaACdAEfo5r8QAD+oec3R7ejGipRi4boNgjSrtm9HkNhqKTnAnzKsl7vOr2fFYmkmb7KhIfcGdXKCcw0kdd+KPiPCpV7E5qdIAAA",
    "focal": {
      "x": 50,
      "y": 45
    },
    "og": false,
    "credit": "Berthold Werner, Public domain, via Wikimedia Commons",
    "author": "Berthold Werner",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Nazaret_Gabrielskirche_BW_11.JPG",
    "file": "Nazaret Gabrielskirche BW 11.JPG"
  },
  {
    "id": "greek-nave-chandeliers",
    "topic": "greek",
    "subject": "interior",
    "alt": "Golden chandeliers and painted pillars inside the Greek Orthodox Church of the Annunciation",
    "width": 1920,
    "height": 1325,
    "widths": [
      640,
      1280,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAABwAgCdASoQAAsAA4BaJYwCdIExgtjFRywDx7gAAP7CUNhd+t0+tBgkLNT03uiyn79qS5C9LEz6Wm8QkopBWBeY8ytqrqw2yZsB0myUzfm1S/T5kygw1CjOgZT312mlqGELnh4A",
    "focal": {
      "x": 50,
      "y": 45
    },
    "og": false,
    "credit": "Zairon / Wikimedia Commons, CC BY-SA 4.0",
    "author": "Zairon",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Nazareth_Orthodoxe_Verk%C3%BCndigungskirche_Innen_2.JPG",
    "file": "Nazareth Orthodoxe Verkündigungskirche Innen 2.JPG"
  },
  {
    "id": "greek-iconostasis",
    "topic": "greek",
    "subject": "iconostasis",
    "alt": "The carved wooden iconostasis of the Greek Orthodox Church of the Annunciation",
    "width": 1920,
    "height": 1400,
    "widths": [
      640,
      1280,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAQCdASoQAAwAA4BaJYwCdADsItbFHAAA/sJMkLZeixsNbevySZfcAEzBt8PeQ1wjG6ux0JYZOPFpdYdexWH1/u+nKYutTbF5RjhTaDvrTikG6iTAAA==",
    "focal": {
      "x": 50,
      "y": 50
    },
    "og": false,
    "credit": "Zairon / Wikimedia Commons, CC BY-SA 4.0",
    "author": "Zairon",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Nazareth_Orthodoxe_Verk%C3%BCndigungskirche_Innen_Ikonostase_1.JPG",
    "file": "Nazareth Orthodoxe Verkündigungskirche Innen Ikonostase 1.JPG"
  },
  {
    "id": "greek-painted-vault",
    "topic": "greek",
    "subject": "ceiling",
    "alt": "A golden chandelier hanging beneath the blue painted vaults of the Greek Orthodox church",
    "width": 1920,
    "height": 1425,
    "widths": [
      640,
      1280,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAACwAQCdASoQAAwAA4BaJaACdABv50OAAP51jBCkaG6mX8pZNRgNWeFl8/cHVmRq8t5f0v+Yxn3h1lZAEyQxpuv1XQ1x/gDFMFPpNgAA",
    "focal": {
      "x": 45,
      "y": 45
    },
    "og": false,
    "credit": "Zairon / Wikimedia Commons, CC BY-SA 4.0",
    "author": "Zairon",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Nazareth_Orthodoxe_Verk%C3%BCndigungskirche_Innen_Decke_3.JPG",
    "file": "Nazareth Orthodoxe Verkündigungskirche Innen Decke 3.JPG"
  },
  {
    "id": "greek-spring-grotto",
    "topic": "greek",
    "subject": "grotto",
    "alt": "The vaulted grotto beneath the Greek Orthodox church, where the spring of Nazareth flows",
    "width": 1920,
    "height": 1280,
    "widths": [
      640,
      1280,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAwAgCdASoQAAsAA4BaJbACdAEf/9Pvp7gQAAD+8OY3YGXu9+URo+DDwXo+rY5bZ+llkSgLIIAwsriPVoYBFwg9rrdwW03V71XKdcabki4vT23VeSqUA7UhmQjh8AAA",
    "focal": {
      "x": 45,
      "y": 50
    },
    "og": false,
    "credit": "Gerd Eichmann / Wikimedia Commons, CC BY-SA 4.0",
    "author": "Gerd Eichmann",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Nazareth-Griechisch-orthodoxe_Verkuendigungskirche-38-Grotte-2010-gje.jpg",
    "file": "Nazareth-Griechisch-orthodoxe Verkuendigungskirche-38-Grotte-2010-gje.jpg"
  },
  {
    "id": "marys-well-arch",
    "topic": "well",
    "subject": "well",
    "alt": "Mary's Well in the centre of Nazareth, a stone arch with three spouts",
    "width": 2560,
    "height": 1707,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAQAgCdASoQAAsAA4BaJYgCdADbZhTahagAAP7078niw21VKZEr9pmAVOJ9a+8Yn1wF/CS1BffZndtEzkGLDmP2kPPFjTFxm14+prPEgAAAAA==",
    "focal": {
      "x": 50,
      "y": 55
    },
    "og": true,
    "credit": "Gerd Eichmann / Wikimedia Commons, CC BY-SA 4.0",
    "author": "Gerd Eichmann",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Nazareth-02-Marienbrunnen-2010-gje.jpg",
    "file": "Nazareth-02-Marienbrunnen-2010-gje.jpg"
  },
  {
    "id": "marys-well-square",
    "topic": "well",
    "subject": "well",
    "alt": "Mary's Well and the paved square around it",
    "width": 1920,
    "height": 1440,
    "widths": [
      640,
      1280,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAQAgCdASoQAAwAA4BaJYgCdAEYGVO1s6TgAP1NfImYQJ5P4c6jpYBHhBFBCRpwM9hrhW/RfkOmMzmPyz8IjEP6Cg6qTCwkfksSRoZos8147fCIdrpQNSyba+KAAA==",
    "focal": {
      "x": 50,
      "y": 55
    },
    "og": false,
    "credit": "Dr. Avishai Teicher / Wikimedia Commons, CC BY 2.5",
    "author": "Dr. Avishai Teicher",
    "license": "CC BY 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:PikiWiki_Israel_28726_Merrys_Well_in_Nazareth.JPG",
    "file": "PikiWiki Israel 28726 Merrys Well in Nazareth.JPG"
  },
  {
    "id": "marys-well-warm-light",
    "topic": "well",
    "subject": "well",
    "alt": "The stone fountain of Mary's Well glowing in warm light",
    "width": 1920,
    "height": 1280,
    "widths": [
      640,
      1280,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoQAAsAA4BaJZACdAEQWm+klgAA/uiJKI+aVVppwGPktzYzA+WW9AT26YSZKIgVDiNlRf8FOp22S61ZndiQrYSEi5L2wwAsbkgAAA==",
    "focal": {
      "x": 50,
      "y": 55
    },
    "og": false,
    "credit": "Kyle Taylor / Wikimedia Commons, CC BY 2.0",
    "author": "Kyle Taylor",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Israel_-_Nazareth_-_39_(4262916857).jpg",
    "file": "Israel - Nazareth - 39 (4262916857).jpg"
  },
  {
    "id": "souk-vaulted-alley",
    "topic": "oldcity",
    "subject": "street",
    "alt": "A quiet vaulted alley of the old souk, its shop doors shut on a Sunday",
    "width": 1920,
    "height": 1280,
    "widths": [
      640,
      1280,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAQCdASoQAAsAA4BaJQBdgCFSaGWLAAD+7EVq1i3pyyqXy+pcG7PLclu3/+vESA7+My8ejHIGgp/VoYPRdcJon3guFWoTd6lfuuSqvIntAAAA",
    "focal": {
      "x": 50,
      "y": 50
    },
    "og": false,
    "credit": "Adam Jones / Wikimedia Commons, CC BY-SA 2.0",
    "author": "Adam Jones",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Doors_and_Vaultings_of_Souk_(Bazaar)_on_a_Sunday_-_Nazareth_-_Israel_(5699103777).jpg",
    "file": "Doors and Vaultings of Souk (Bazaar) on a Sunday - Nazareth - Israel (5699103777).jpg"
  },
  {
    "id": "souk-arcade",
    "topic": "oldcity",
    "subject": "market",
    "alt": "A stone arcade of the old market with green shop doors",
    "width": 1920,
    "height": 1198,
    "widths": [
      640,
      1280,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAQAgCdASoQAAoAA4BaJZQCdAEC13XRgsAAAP6mwXzvKU8MogAC2yo/vDozVCyRQs7Zh236WauZHgHY0/yIT2xHnYxtnwoUD3lDAAAA",
    "focal": {
      "x": 50,
      "y": 50
    },
    "og": false,
    "credit": "Zairon / Wikimedia Commons, CC BY-SA 4.0",
    "author": "Zairon",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Nazareth_Suq.JPG",
    "file": "Nazareth Suq.JPG"
  },
  {
    "id": "old-city-green-doors",
    "topic": "oldcity",
    "subject": "street",
    "alt": "A narrow lane of the Old City between stone houses and green doors",
    "width": 1920,
    "height": 1440,
    "widths": [
      640,
      1280,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAwAgCdASoQAAwAA4BaJYgCdAYsFtmrnvRC3ADOCZV+CT/+T0vtNQTFtxNm6eiuQz71EBbd5GyTX7d3S37Gq1971LEAr+uQN1GsmcSXs1QCvlwYFT/wBGMVbEHzT/IAAAA=",
    "focal": {
      "x": 55,
      "y": 50
    },
    "og": false,
    "credit": "ישראל פרקר / Wikimedia Commons, CC BY 2.5",
    "author": "ישראל פרקר",
    "license": "CC BY 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:PikiWiki_Israel_83464_old_nazareth.jpg",
    "file": "PikiWiki Israel 83464 old nazareth.jpg"
  },
  {
    "id": "old-city-arched-passage",
    "topic": "oldcity",
    "subject": "street",
    "alt": "A vaulted passage in the Old City with flowers trailing over the doorways",
    "width": 2560,
    "height": 1920,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "blurDataURL": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAQAgCdASoQAAwAA4BaJQBOgCBTENcGHxWAAOJv6Yzj4sgNpukhp3otSqXQCE2O15JgIgKOsW/JUGGz/xgJYtodrCV5qKv/wYei4H5Hki3Mp3VBV8BD8XagtamaQAAA",
    "focal": {
      "x": 50,
      "y": 45
    },
    "og": true,
    "credit": "ישראל פרקר / Wikimedia Commons, CC BY 2.5",
    "author": "ישראל פרקר",
    "license": "CC BY 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:PikiWiki_Israel_83466_old_nazareth.jpg",
    "file": "PikiWiki Israel 83466 old nazareth.jpg"
  },
  {
    "id": "old-city-lights",
    "topic": "oldcity",
    "subject": "exterior",
    "alt": "Old stone houses of the Old City hung with strings of lights",
    "width": 1920,
    "height": 1198,
    "widths": [
      640,
      1280,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoQAAoAA4BaJQBOj+ADB6J048AA/uAGMHITdeshDnfNJPwfcBWOpWwt7L+12oHPx1crLtuGpULCpCrunmg1iAAA",
    "focal": {
      "x": 50,
      "y": 50
    },
    "og": false,
    "credit": "ישראל פרקר / Wikimedia Commons, CC BY 2.5",
    "author": "ישראל פרקר",
    "license": "CC BY 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:PikiWiki_Israel_83460_old_nazareth.jpg",
    "file": "PikiWiki Israel 83460 old nazareth.jpg"
  },
  {
    "id": "synagogue-church-altar",
    "topic": "synagogue",
    "subject": "altar",
    "alt": "The vaulted stone chapel and altar of the Synagogue Church",
    "width": 1920,
    "height": 1280,
    "widths": [
      640,
      1280,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQAgCdASoQAAsAA4BaJbACdADRNq8wL6GgAPaAlbG3uNF4Tg+r5y/zn/nKYcgzzBKmUDfsu0umBrCGtLvUUirBXWctF9qpWSH8G7+Iqe4zBrpa/wAAAA==",
    "focal": {
      "x": 50,
      "y": 60
    },
    "og": false,
    "credit": "כובש המלפפונים / Wikimedia Commons, CC BY-SA 4.0",
    "author": "כובש המלפפונים",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:SynagogueChurchNazareth.jpg",
    "file": "SynagogueChurchNazareth.jpg"
  },
  {
    "id": "synagogue-church-vault",
    "topic": "synagogue",
    "subject": "interior",
    "alt": "The long barrel-vaulted hall of the Synagogue Church, built of old stone",
    "width": 1920,
    "height": 1440,
    "widths": [
      640,
      1280,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAQCdASoQAAwAA4BaJagCdACIrJBnAAD8cPEOnIQRkXUl/S40m0LacC3SopoDsP+ewK1MHQqH1CQc76gFNCjzqV5eqROqQue40oK8+4AcAA==",
    "focal": {
      "x": 50,
      "y": 55
    },
    "og": false,
    "credit": "שלמה רודד / Wikimedia Commons, CC BY 2.5",
    "author": "שלמה רודד",
    "license": "CC BY 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:127769_nazareth-synagogue_church_PikiWiki_Israel.jpg",
    "file": "127769 nazareth-synagogue church PikiWiki Israel.jpg"
  },
  {
    "id": "synagogue-church-melkite-nave",
    "topic": "synagogue",
    "subject": "interior",
    "alt": "The Melkite Greek Catholic church next to the Synagogue Church, with chandeliers and a red carpet",
    "width": 1920,
    "height": 1080,
    "widths": [
      640,
      1280,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAQCdASoQAAkAA4BaJbACdAEKDAsszzAA+wX5/YogqXuk21xJadJmxE0qOBmr5KUE4SLNv/X3nU/N4GED/hbvmC5jLYLGPg4Ex2yKJpkF6mwHLO06AAAA",
    "focal": {
      "x": 50,
      "y": 50
    },
    "og": false,
    "credit": "israel zeller / Wikimedia Commons, CC BY 2.5",
    "author": "israel zeller",
    "license": "CC BY 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:PikiWiki_Israel_67285_a_melakit_greek_church_in_nazareth.jpg",
    "file": "PikiWiki Israel 67285 a melakit greek church in nazareth.jpg"
  },
  {
    "id": "precipice-olive-viewpoint",
    "topic": "precipice",
    "subject": "panorama",
    "alt": "An olive tree on the viewpoint of Mount Precipice, looking out over the Jezreel Valley",
    "width": 1920,
    "height": 1440,
    "widths": [
      640,
      1280,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAwAgCdASoQAAwAA4BaJZACdAD7VG4I27zQgADydDtk989FoVpLi0l9WusH3jaTWGeInP1bIM237X9LpK8iA+5btV1n0PVQWFkDk2w1+MWhWRtgkmM6dIoAAAA=",
    "focal": {
      "x": 50,
      "y": 45
    },
    "og": false,
    "credit": "Dr. Avishai Teicher / Wikimedia Commons, CC BY 2.5",
    "author": "Dr. Avishai Teicher",
    "license": "CC BY 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:PikiWiki_Israel_28735_Mount_of_Precipice.JPG",
    "file": "PikiWiki Israel 28735 Mount of Precipice.JPG"
  },
  {
    "id": "precipice-cliff",
    "topic": "precipice",
    "subject": "hills",
    "alt": "The rocky face of Mount Precipice, the Mount of the Leap above Nazareth",
    "width": 1920,
    "height": 1440,
    "widths": [
      640,
      1280,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADQAQCdASoQAAwAA4BaJZQCw7EMV02oyAD+8BbqHFw4dvEwO22lmQObrlnj6UCfbHmAPp6w3lxdmKaqL2IY6RLTcQpEtsE1z0epMAAA",
    "focal": {
      "x": 55,
      "y": 45
    },
    "og": false,
    "credit": "Dr. Avishai Teicher / Wikimedia Commons, CC BY 2.5",
    "author": "Dr. Avishai Teicher",
    "license": "CC BY 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:PikiWiki_Israel_30995_Mount_Precipice.JPG",
    "file": "PikiWiki Israel 30995 Mount Precipice.JPG"
  },
  {
    "id": "precipice-valley-pine",
    "topic": "precipice",
    "subject": "panorama",
    "alt": "A pine tree on Mount Precipice above the fields of the Jezreel Valley",
    "width": 1920,
    "height": 1046,
    "widths": [
      640,
      1280,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADQAQCdASoQAAkAA4BaJYgCdAEIk7KPAAD8L8/V6SeuFvpX8KhcyuA9XEQFDZ22jcSRe/d2YUjvL1ZzNmZCrSzRF7DNja9MlIlZKq+xWR56GAgshgeGFRsVIh4AAA==",
    "focal": {
      "x": 50,
      "y": 55
    },
    "og": false,
    "credit": "ישראל פרקר / Wikimedia Commons, CC BY 2.5",
    "author": "ישראל פרקר",
    "license": "CC BY 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:98575_mount_precipice_PikiWiki_Israel.jpg",
    "file": "98575 mount precipice PikiWiki Israel.jpg"
  },
  {
    "id": "city-basilica-skyline",
    "topic": "city",
    "subject": "skyline",
    "alt": "The Basilica of the Annunciation among the hillside houses of Nazareth under a blue sky",
    "width": 2560,
    "height": 1707,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAAAwAgCdASoQAAsAA4BaJaACdGuAAswHL+3IAAD7j1az1+IJi+bUKtTNkHyTwesvQajlo3La1HBg7KBhrzebZUEGl0DV0n43JUCAAA==",
    "focal": {
      "x": 74,
      "y": 45
    },
    "og": true,
    "credit": "Israel_photo_gallery / Wikimedia Commons, CC BY-SA 2.0",
    "author": "Israel_photo_gallery",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Nazareth_Panorama_Dafna_Tal_IMOT_(14532097313).jpg",
    "file": "Nazareth Panorama Dafna Tal IMOT (14532097313).jpg"
  },
  {
    "id": "city-churches-minaret",
    "topic": "city",
    "subject": "skyline",
    "alt": "Nazareth in warm light: church towers, a minaret and homes climbing the hillside",
    "width": 1920,
    "height": 1440,
    "widths": [
      640,
      1280,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAwAgCdASoQAAwAA4BaJYgCdAEPh6kflYhAAAD94yFp+WV8Hr2N1abosxzWbajosJ+mdXg4Y0IjWkNOtVlH9mpJMf6gPPYFARw90WAA",
    "focal": {
      "x": 60,
      "y": 45
    },
    "og": false,
    "credit": "רונן מרקוס / Wikimedia Commons, CC BY 2.5",
    "author": "רונן מרקוס",
    "license": "CC BY 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:PikiWiki_Israel_51454_panorama_of_the_city_of_nazareth.jpg",
    "file": "PikiWiki Israel 51454 panorama of the city of nazareth.jpg"
  },
  {
    "id": "city-hills-galilee",
    "topic": "city",
    "subject": "panorama",
    "alt": "Nazareth below the hills of Galilee, seen from the heights",
    "width": 2560,
    "height": 1700,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "blurDataURL": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAAAQAgCdASoQAAsAA4BaJQBOj+ADBB1Dmq94AP6MOvGt9fipH09S3rYsomQhxAa1XsrUjD83TOgdKqTBP03VaMAA",
    "focal": {
      "x": 30,
      "y": 60
    },
    "og": true,
    "credit": "Neil Ward / Wikimedia Commons, CC BY 2.0",
    "author": "Neil Ward",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Nazareth_from_a_394_step_height_(7755448620).jpg",
    "file": "Nazareth from a 394 step height (7755448620).jpg"
  },
  {
    "id": "city-sunset-glow",
    "topic": "city",
    "subject": "skyline",
    "alt": "Nazareth glowing at sunset, with the Basilica of the Annunciation lit among the rooftops",
    "width": 2560,
    "height": 1707,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAQAgCdASoQAAsAA4BaJbACdAEe/8r9JWVwAP6HuJ3JBeUrattiuLRN5Xm+c/K6zdKbVyTqEABFb3poHZeb+oyIuFtDsO5ga72ikbiAAAA=",
    "focal": {
      "x": 25,
      "y": 60
    },
    "og": true,
    "credit": "Liran1977 / Wikimedia Commons, CC BY-SA 3.0",
    "author": "Liran1977",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:%D7%9B%D7%A0%D7%A1%D7%99%D7%99%D7%AA_%D7%94%D7%91%D7%A9%D7%95%D7%A8%D7%94_%D7%A0%D7%A6%D7%A8%D7%AA.jpg",
    "file": "כנסיית הבשורה נצרת.jpg"
  },
  {
    "id": "city-snow",
    "topic": "city",
    "subject": "skyline",
    "alt": "Snow on the rooftops of Nazareth with the dome of the Basilica in the middle",
    "width": 1920,
    "height": 1080,
    "widths": [
      640,
      1280,
      1920
    ],
    "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAAAwAgCdASoQAAkAA4BaJQBOj+ADA3mqXkvAAAD+apfGcFBblfS5LwYhE8imXucvFFSV44nPUx5K8RErjza8xbRHUuzUTmlAAAA=",
    "focal": {
      "x": 60,
      "y": 60
    },
    "og": false,
    "credit": "Andrewfarah.a / Wikimedia Commons, CC BY-SA 4.0",
    "author": "Andrewfarah.a",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Snow_in_Nazareth.jpg",
    "file": "Snow in Nazareth.jpg"
  }
];
