// Types of the licensed Nazareth imagery (see docs/MEDIA.md). The data itself is generated by
// scripts/media/build.mjs into media.generated.ts; read it through the helpers in media.ts.

/** What a photo shows. Each topic has a translated name (media.topic.*) and belongs to one holy-site page. */
export const MEDIA_TOPICS = [
  'basilica',
  'stjoseph',
  'greek',
  'well',
  'oldcity',
  'synagogue',
  'precipice',
  'city',
] as const;
export type MediaTopic = (typeof MEDIA_TOPICS)[number];

/** What is in the frame. Each subject has a translated phrase (media.subject.*) used in the alt text. */
export const MEDIA_SUBJECTS = [
  'facade',
  'exterior',
  'dome',
  'courtyard',
  'interior',
  'grotto',
  'altar',
  'iconostasis',
  'ceiling',
  'bellTower',
  'well',
  'market',
  'street',
  'skyline',
  'panorama',
  'hills',
  'night',
] as const;
export type MediaSubject = (typeof MEDIA_SUBJECTS)[number];

export type MediaItem = {
  /** Stable id, also the folder name under /images/nazareth-media/. */
  id: string;
  topic: MediaTopic;
  subject: MediaSubject;
  /** English alt text (the pages build a translated one from topic + subject). */
  alt: string;
  /** Pixel size of the largest file. */
  width: number;
  height: number;
  /** Widths of the generated AVIF/WebP files, ascending. */
  widths: readonly number[];
  /** 16px wide WebP as a data: URL, shown while the photo loads. */
  blurDataURL: string;
  /** Where to centre a crop, in percent of the width/height. */
  focal: { x: number; y: number };
  /** True when a 1200x630 social card (og.jpg) was generated. */
  og: boolean;
  /** "Author / Wikimedia Commons, CC BY-SA 4.0" */
  credit: string;
  author: string;
  license: string;
  licenseUrl: string;
  /** The Wikimedia Commons file page. */
  sourceUrl: string;
  /** The Commons file name, without the "File:" prefix. */
  file: string;
};
